# Site settings
name: Navbar
title: Navbar
email: 
description: > # this means to ignore newlines until "baseurl:"
  Navbar
# baseurl:  # the subpath of your site, e.g. /blog/
url: "http://localhost:3000" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

# Build settings
markdown: kramdown

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - README.md
  - .jekyll-cache
  - bootstrap-vars.scss
  - vendor

keep_files:
  - _site/css
  - _site/js

include: ['_pages']
